sudo: required
services: 
  - docker

before_install:
  - docker build -t michaeljohnson422/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true michaeljohnson422/docker-react npm run test

language: generic
