sudo: required
services: 
  - docker

before_install:
  - docker build -t michaeljohnson422/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true michaeljohnson422/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucker_name: "elasticbeanstalk-us-east-2-717024191043"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
# Access key ID:  AKIA2N4PY4JB74HFH5UK
# Secret Access Key:  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
language: generic
