sudo: required
services: 
  - docker

before_install:
  - docker build -t michaeljohnson422/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true michaeljohnson422/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-env2"
  env: "DockerEnv2-env"
  bucket_name: "elasticbeanstalk-us-east-2-717024191043"
  bucket_path: "Docker-env2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

language: generic
